### PR TITLE
v0.6.1 / v0.6.2 merges

### PR DESCRIPTION
**Pull request by mcm1957**
The following changes / improvements are included in this pull request:

### 0.6.2
* (McM1957) rename state IP.info.connected to IP.online

### 0.6.1
* (McM1957) reduce severity of timout message to informational
* (McM1957) reduce latency for update of info.connection 
* (McM1957) update dependencies as suggested by dependabot

### 0.6.0
* (McM1957) avoid excessive error logs if target is unreachable
* (McM1957) add additional info.connection at ip base to indicate target is reachable
* (McM1957) output warning if OIDs specify different commmunities for one device

### CODE REVIEW

**Comment by Apollon77** [comment]
Looks good ... Do we really need the IP.info.connected ... or can we not easiy use IP.connected ? ... We dio not need that channel in my eyes ... or are there reasons?

**Comment by Apollon77** [comment]
in fact .online is commonly used, but .connected also ... so both fine ... I think .online makes mrore sense in this case because it is no "standing connection"... right?

**Comment by mcm1957** [comment]
Your right. There's no permanent connection (at least as far as I know, not 100% sure what the snmp library does). 

It indicates whether a communication was possibel during the last poll. You could achive this by reading the timestamps of the states too (- at least I think that this would be possible -) but I think a dedicated state for one ip (one device) is ok and useable.

So I will change the state name to ".online".

**Comment by Apollon77** [comment]
Thank you!

Aftr that I will merge and then give some "general things" a overhaul before we release

**Comment by mcm1957** [comment]
I've changed to code and updated the release number to avoid confusing others that eventually installed v0.6.1.

Looks like the changes made oits way into the PR automatically. Is this correct - or do I have to release something explicitly?

(Not related to this PR but as GIT novice I would like to know what I should have done if I would have preferred that v0.6.2 does NOT get into this PR, for example if v0.6.2 has bigger changes and should be tested some time ... ? Looks like commits to my master get automatically added to this PR ...)

**Comment by Apollon77** [comment]
In fact I will add the release,script then from then on nooen adjusts versions manually :-) Will be handled automatically, so all fine :-)  Will check

**Comment by mcm1957** [comment]
> In fact I will add the release,script then from then on nooen adjusts versions manually 

Guess it was late already. I do not understand this sentence. Maybe google translated it with chinese intemediate language. :-)
Or cut and paste inserted some stuff ..

But it sounds like everything is ok and no action is required by me.

I'll take a cup of coffee. If any help is needed from me let me know. The only real open question is why this PR has been extended only by committing something to mcm1957/iobroker.snmp master after the PR has been created. I would like to know how to avoid this.

**Comment by Apollon77** [comment]
I updated anything else :-)) infuture please provide changelog as seen in readme right now ... https://github.com/iobroker-community-adapters/ioBroker.snmp/commit/3660c9305b0a303494a8bee39db52673b0f0e35d

**Comment by Apollon77** [comment]
@mcm1957 I did some more updates and es6 conversion ... https://github.com/iobroker-community-adapters/ioBroker.snmp/commit/f7c43d04855a046b3eb32492af99abb437f280f9

Can you give this version a try please to see that I did not broke stuff? ;-)

**Comment by mcm1957** [comment]
>>I updated anything else :-)) 
Thanks. I guess it will take years until I understand what those file do :-). 

>>infuture please provide changelog as seen in readme right now ... 
Please confirm that the major thing to respect is that I should NOT use version numbers but add changes after the generic entry  "### __WORK IN PROGRESS__". I assume that this label will be changes during processing automatically. Is this correct?
The other changes refer to header / counter etc which you updated to current standard. Or do I overlook anything important?

McM

**Comment by mcm1957** [comment]
> Can you give this version a try please to see that I did not broke stuff? ;-)

It's hard to check as git listes the complete Module main.js as changed. Don't know what has changed to cause this.

The module seems to work

BUT
Naming of state IDs has changed definitly. The old version incl. my version used some folderstructure (i.e. fuser_unit with elements name, status and total while now the ids are displyed flat as fuser_unit_name, fuser_unit_status and fuser_unit_total). I do not know whether you changed this on purpose or if this change is some sideeffect. (I even do not know how the directory like structure was created). I want to point to issue #19 which request such a sub datapoint handling. 

Please let me know whether you changed this on purpose.

McM

**Comment by mcm1957** [comment]
Heres an example 
The folders have been creted with 0.6.2. The flat names with master from github repository:
 
image

**Comment by Apollon77** [comment]
Exactly ... in fact I did that change because of #14 :-) so ...... hhhmmm ... and yes all the ones with "." are also strange.

The problem with "." is that it will display like a "folder structure" but in fact the in between objects will be missing (unless we create them manually - we can do, no issue ...)

In fact we can do a 1.0 and "break" the structire ... if it makes sense also no issue.

Ok, so proposal: I replace "forbidden, but non ." in names by _ and we will preserve "." ... and I automatically create the missing folders

**Comment by mcm1957** [comment]
@Apollon77 
Hi Ingo,
I evalute to improve the snmp adapter. But I'm not sure whether I should implement an snmp-plus adapter or continue work at this adapter. Where can we discuss this best? Should I open a topic at forum.iobroker.net / entwickliung? Or is some other place better. I short I think about a complete rewrite based on adapter creator code to get current "standards", add snmp v3, add multiple timers per IP, etc. But as this is not the best place for a discussion, please advice wher I could reach you and other interested developers best.
Martin

**Comment by Apollon77** [comment]
For the topic here now ... here my proposal: https://github.com/iobroker-community-adapters/ioBroker.snmp/commit/f55153e7961d383f2130628b730419f143f094f4

For the other. In fact Forum, Discord or Telegram are all three good channels.
Question is if a new adapter is best or if we not just replace this one by a new version. With a major release we can also "break" object structures or such ... so ..... you can also adjust in this repo  :-)

**Comment by mcm1957** [comment]
@Apollon77 

Concerning the Discussion topic:
I will open a thread at the forum later. I (currently) do not know or use discord - I will have to check whether to use. Telegram is available and would be ok if you dont mind - but I do not know how to contact you or send my phone number without posting to the whole world here :-) 

P.S: I'm going to check your proposal - but feedback might last until tomorrow as I will read and try to understand the issue with folders first and why theres a (incompatible) change in structure.

Martin

**Comment by Apollon77** [comment]
Telegram: just search me with name as on GitHub ;-)

**Comment by mcm1957** [comment]
Ok, I will try to summarize

OLD object  structure (current stable v0.5.0, v0.6.1)  was

image

NEW object structure proposed yesterday (f7c43d0) was flat:

image

NEW object structure proposednow (f55153e) is:

image

So if I understand the whole thing correctly, ANY of the two changes will change the object structure. So if we want to solve issue #19 a break within the objet structure is required. (I did not check whether issue #14 could be solved while keeping the old structure.) But as the old struture is somehow incomnsistent anyway (the first dot is replade but more dots are not) I think breaking the structure will be ok.

Maybe a hint at the releasenotes stating that manually renaming the objects (replacing the first dot by underscore) could / should help keeping the current structure would be useful.

One more remark:
You add a name to the folders now (IP.name). Currently did not have names. I do not know whether folders shoudl have names or not - you know better for sure. BUT I notice that you prepend the IP to those names. The objectnames do NOT have the IP prepended. I'm not sure wheter th IP is required or suggested. Readability is better wiothout the IP in my oppinion. But if the name should (or even must) be unique - the IP should be added at the state name too.

Martin

P.S. My planned changes (- datails to be discussed -) include a change in configuration, namely a split in to tables, one for the devide (IP) and one for the OIDs. This would NOT result in a change of the object structure. But would this require an additional incompatible change version jump? Would this be accepted by users?

**Pull request merged**
